---
title: Leveraging Economic Policy
timezone: America/New_York
collections:
  Pos:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
permalink: "/:title"
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
exclude:
- ".gitignore"
- node-modules
description: 'Marketing site for DAI’s portfolio of work on Public Financial Management'
baseurl:
destination: "./build"
sass:
  style: compressed
